import React from 'react'
import Table from './table'
import madras from "../68f4a0d09c4111471f3fd768d5d56312.jpg"

const MainComponent = () => {
    let collegeList =[
        {
         cdRank:1,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        },
        {
            cdRank:2,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 109550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:7.6,
          totalUser:289,
          rank:1,
          featured:true,
          totalRank:131,
        },
        {
            cdRank:3,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        },
        {
          cdRank:4,
          collegeName:"IIT Bombay - Indian Institute of technology - (IITB), Bombay",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        },
        {
          cdRank:5,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        },
        {
            cdRank:6,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 109550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:7.6,
          totalUser:289,
          rank:1,
          totalRank:131,
        },
        {
            cdRank:7,
          collegeName:"IIT Madras - Indian Institute of technology - (IITM), Chennai",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        },
        {
          cdRank:8,
          collegeName:"IIT Bombay - Indian Institute of technology - (IITB), Bombay",
          location: "Chennai, Tamil Nadu | AICTE Approved",
          image:madras,
          course:"B.Tech Computer Science Engineering",
          cutoff:144,
          courseFees:" 209550",
          avgPackage:"21,48,000",
          highPackage:"1,98,00,000",
          userReview:8.6,
          totalUser:289,
           rank:3,
          featured:false,
          totalRank:131,
        }
      ]
  return (
    <div>
        <Table collegeList={collegeList} />
    </div>
  )
}

export default MainComponent